routes/web.php
<?php

//per la cache
//https://github.com/JosephSilber/page-cache

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\StaticController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\GalleriesController;
use App\Http\Controllers\ContactController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::middleware('page-cache')->get('/', [StaticController::class, 'index'])->name('static');
Route::middleware('page-cache')->get('/chi-siamo', [StaticController::class, 'about'])->name('about');
Route::middleware('page-cache')->get('/richiedi-assistenza', [StaticController::class, 'assistence'])->name('assistence');
Route::middleware('page-cache')->get('/cookie-policy', [StaticController::class, 'cookie'])->name('cookie');
Route::middleware('page-cache')->get('/privacy-policy', [StaticController::class, 'privacy'])->name('privacy');
Route::middleware('page-cache')->get('/servizi', [StaticController::class, 'services'])->name('services');
Route::middleware('page-cache')->get('/galleria', [StaticController::class, 'gallery'])->name('galleriesfront');

//Route::get('/', [StaticController::class, 'index'])->name('static');
//Route::get('/chi-siamo', [StaticController::class, 'about'])->name('about');
//Route::get('/richiedi-assistenza', [StaticController::class, 'assistence'])->name('assistence');
//Route::get('/cookie-policy', [StaticController::class, 'cookie'])->name('cookie');
//Route::get('/privacy-policy', [StaticController::class, 'privacy'])->name('privacy');
//Route::get('/servizi', [StaticController::class, 'services'])->name('services');
//Route::get('/galleria', [StaticController::class, 'gallery'])->name('galleriesfront');

//Route::middleware('page-cache')->get('/contatti', [StaticController::class, 'contact'])->name('contact');

//Route::get('/', [StaticController::class, 'index'])->name('static');
//Route::get('/chi-siamo', [StaticController::class, 'about'])->name('about');
//Route::get('/richiedi-assistenza', [StaticController::class, 'assistence'])->name('assistence');
//Route::get('/cookie-policy', [StaticController::class, 'cookie'])->name('cookie');
//Route::get('/privacy-policy', [StaticController::class, 'privacy'])->name('privacy');

//Route::get('/servizi', [StaticController::class, 'services'])->name('services');
//Route::get('/galleria', [StaticController::class, 'gallery'])->name('galleriesfront');

Route::get('/contatti', [StaticController::class, 'contact'])->name('contact');
Route::post('/contatti', [ContactController::class, 'store'])->name('contact.store');


//Route::get('/login', [AdminController::class, 'index'])->name('login');

Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function() {

    Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard');
    Route::get('/users/data/', [UserController::class, 'data'])->name('users.data');
    Route::resource('users', UserController::class);

    //roles
    Route::get('/roles/data/', [RoleController::class, 'data'])->name('roles.data');
    Route::resource('roles', RoleController::class);

    //pages
    Route::get('/pages/data/', [PagesController::class, 'data'])->name('pages.data');
    Route::resource('pages', PagesController::class);

    //galleries
    Route::get('/galleries/data/', [GalleriesController::class, 'data'])->name('galleries.data');
    Route::resource('galleries', GalleriesController::class);
});

Auth::routes();

resources/views/partials/admin/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; 2022 Vincenzo Flauto.</strong>
    Tutti i diritti riservati.
    <div class="float-right d-none d-sm-inline-block">
        <b>Versione</b> 2.0.1
    </div>
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->

resources/views/partials/admin/header.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('plugins/fontawesome-free/css/all.min.css') }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="{{ asset('plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{ asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{{ asset('plugins/jqvmap/jqvmap.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('css/adminlte.min.css') }}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{{ asset('plugins/overlayScrollbars/css/OverlayScrollbars.min.css') }}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{ asset('plugins/daterangepicker/daterangepicker.css') }}">
    <!-- summernote -->
    <link rel="stylesheet" href="{{ asset('plugins/summernote/summernote-bs4.min.css') }}">
    <!-- SweetAlert2 -->
    <link rel="stylesheet" href="{{ asset('plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css') }}">
    <!-- Toast -->
    <link rel="stylesheet" href="{{ asset('plugins/toastr/toastr.min.css') }}">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    @stack('head-script')
</head>

resources/views/partials/admin/navbar.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
{{--        <li class="nav-item">--}}
{{--            <a class="nav-link" data-widget="navbar-search" href="#" role="button">--}}
{{--                <i class="fas fa-search"></i>--}}
{{--            </a>--}}
{{--            <div class="navbar-search-block">--}}
{{--                <form class="form-inline">--}}
{{--                    <div class="input-group input-group-sm">--}}
{{--                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">--}}
{{--                        <div class="input-group-append">--}}
{{--                            <button class="btn btn-navbar" type="submit">--}}
{{--                                <i class="fas fa-search"></i>--}}
{{--                            </button>--}}
{{--                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">--}}
{{--                                <i class="fas fa-times"></i>--}}
{{--                            </button>--}}
{{--                        </div>--}}
{{--                    </div>--}}
{{--                </form>--}}
{{--            </div>--}}
{{--        </li>--}}

        <!-- Messages Dropdown Menu -->
{{--        <li class="nav-item dropdown">--}}
{{--            <a class="nav-link" data-toggle="dropdown" href="#">--}}
{{--                <i class="far fa-comments"></i>--}}
{{--                <span class="badge badge-danger navbar-badge">3</span>--}}
{{--            </a>--}}
{{--            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">--}}
{{--                <a href="#" class="dropdown-item">--}}
{{--                    <!-- Message Start -->--}}
{{--                    <div class="media">--}}
{{--                        <img src="{{ asset('img/user1-128x128.jpg') }}" alt="User Avatar" class="img-size-50 mr-3 img-circle">--}}
{{--                        <div class="media-body">--}}
{{--                            <h3 class="dropdown-item-title">--}}
{{--                                Brad Diesel--}}
{{--                                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>--}}
{{--                            </h3>--}}
{{--                            <p class="text-sm">Call me whenever you can...</p>--}}
{{--                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>--}}
{{--                        </div>--}}
{{--                    </div>--}}
{{--                    <!-- Message End -->--}}
{{--                </a>--}}
{{--                <div class="dropdown-divider"></div>--}}
{{--                <a href="#" class="dropdown-item">--}}
{{--                    <!-- Message Start -->--}}
{{--                    <div class="media">--}}
{{--                        <img src="{{ asset('img/user8-128x128.jpg') }}" alt="User Avatar" class="img-size-50 img-circle mr-3">--}}
{{--                        <div class="media-body">--}}
{{--                            <h3 class="dropdown-item-title">--}}
{{--                                John Pierce--}}
{{--                                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>--}}
{{--                            </h3>--}}
{{--                            <p class="text-sm">I got your message bro</p>--}}
{{--                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>--}}
{{--                        </div>--}}
{{--                    </div>--}}
{{--                    <!-- Message End -->--}}
{{--                </a>--}}
{{--                <div class="dropdown-divider"></div>--}}
{{--                <a href="#" class="dropdown-item">--}}
{{--                    <!-- Message Start -->--}}
{{--                    <div class="media">--}}
{{--                        <img src="{{ asset('img/user3-128x128.jpg') }}" alt="User Avatar" class="img-size-50 img-circle mr-3">--}}
{{--                        <div class="media-body">--}}
{{--                            <h3 class="dropdown-item-title">--}}
{{--                                Nora Silvester--}}
{{--                                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>--}}
{{--                            </h3>--}}
{{--                            <p class="text-sm">The subject goes here</p>--}}
{{--                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>--}}
{{--                        </div>--}}
{{--                    </div>--}}
{{--                    <!-- Message End -->--}}
{{--                </a>--}}
{{--                <div class="dropdown-divider"></div>--}}
{{--                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>--}}
{{--            </div>--}}
{{--        </li>--}}
        <!-- Notifications Dropdown Menu -->
{{--        <li class="nav-item dropdown">--}}
{{--            <a class="nav-link" data-toggle="dropdown" href="#">--}}
{{--                <i class="far fa-bell"></i>--}}
{{--                <span class="badge badge-warning navbar-badge">15</span>--}}
{{--            </a>--}}
{{--            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">--}}
{{--                <span class="dropdown-item dropdown-header">15 Notifications</span>--}}
{{--                <div class="dropdown-divider"></div>--}}
{{--                <a href="#" class="dropdown-item">--}}
{{--                    <i class="fas fa-envelope mr-2"></i> 4 new messages--}}
{{--                    <span class="float-right text-muted text-sm">3 mins</span>--}}
{{--                </a>--}}
{{--                <div class="dropdown-divider"></div>--}}
{{--                <a href="#" class="dropdown-item">--}}
{{--                    <i class="fas fa-users mr-2"></i> 8 friend requests--}}
{{--                    <span class="float-right text-muted text-sm">12 hours</span>--}}
{{--                </a>--}}
{{--                <div class="dropdown-divider"></div>--}}
{{--                <a href="#" class="dropdown-item">--}}
{{--                    <i class="fas fa-file mr-2"></i> 3 new reports--}}
{{--                    <span class="float-right text-muted text-sm">2 days</span>--}}
{{--                </a>--}}
{{--                <div class="dropdown-divider"></div>--}}
{{--                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>--}}
{{--            </div>--}}
{{--        </li>--}}
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
{{--        <li class="nav-item">--}}
{{--            <a class="nav-link" data-widget="control-sidebar" data-controlsidebar-slide="true" href="#" role="button">--}}
{{--                <i class="fas fa-th-large"></i>--}}
{{--            </a>--}}
{{--        </li>--}}
    </ul>
</nav>
<!-- /.navbar -->

resources/views/partials/admin/sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/" class="brand-link">
        <img src="{{ asset('img/telephonehelp_logo_negativo.png') }}" alt="Telephone Help Logo" class="brand-image elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">&nbsp;</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
{{--            <div class="image">--}}
{{--                <img src="{{ asset('img/user2-160x160.jpg') }}" class="img-circle elevation-2" alt="User Image">--}}
{{--            </div>--}}
            <div class="info">
                <a href="#" class="d-block">{{ Auth::user()->name}} {{ Auth::user()->surname}}</a>
            </div>
        </div>

        <!-- SidebarSearch Form -->
{{--        <div class="form-inline">--}}
{{--            <div class="input-group" data-widget="sidebar-search">--}}
{{--                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">--}}
{{--                <div class="input-group-append">--}}
{{--                    <button class="btn btn-sidebar">--}}
{{--                        <i class="fas fa-search fa-fw"></i>--}}
{{--                    </button>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a href="{{ route('dashboard') }}" class="nav-link @if(isset($activeMenuHome) && $activeMenuHome == true) active @endif">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>
                <li class="nav-header">Pagine</li>
                @can('Vedi Pagine')
                    <li class="nav-item">
                        <a href="{{ route('pages.index') }}" class="nav-link @if(isset($activeMenuPages) && $activeMenuPages == true) active @endif">
                            <i class="nav-icon fas fa-list"></i>
                            <p>
                                Pagine
                            </p>
                        </a>
                    </li>
                @endcan
                <li class="nav-header">Video</li>
                @can('Vedi Galleria')
                    <li class="nav-item">
                        <a href="{{ route('galleries.index') }}" class="nav-link @if(isset($activeMenuGallery) && $activeMenuGallery == true) active @endif">
                            <i class="nav-icon fas fa-list"></i>
                            <p>
                                Video
                            </p>
                        </a>
                    </li>
                @endcan
                <li class="nav-header">{{__("app.settings")}}</li>
                @can('Vedi Utente')
                <li class="nav-item">
                    <a href="{{ route('users.index') }}" class="nav-link @if(isset($activeMenuUsers) && $activeMenuUsers == true) active @endif">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            {{__("app.users")}}
                        </p>
                    </a>
                </li>
                @endcan
                @can('Vedi Ruolo')
                <li class="nav-item">
                    <a href="{{ route('roles.index') }}" class="nav-link @if(isset($activeMenuRoles) && $activeMenuRoles == true) active @endif">
                        <i class="nav-icon fas fa-user"></i>
                        <p>
                            {{__("app.roles")}}
                        </p>
                    </a>
                </li>
                @endcan
{{--                @can('Vedi Azienda')--}}
{{--                <li class="nav-item">--}}
{{--                    <a href="{{ route('companies.index') }}" class="nav-link @if(isset($activeMenuCompanies) && $activeMenuCompanies == true) active @endif">--}}
{{--                        <i class="nav-icon fas fa-house-user"></i>--}}
{{--                        <p>--}}
{{--                            {{__("app.companies")}}--}}
{{--                        </p>--}}
{{--                    </a>--}}
{{--                </li>--}}
{{--                @endcan--}}
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <form action="{{ route('logout') }}" method="POST">
                            @csrf
                            <button type="submit" class="btn btn-danger">
                                <i class="nav-icon fas fa-sign-out-alt"></i> {{ __('Logout') }}
                            </button>
                        </form>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>