routes/web.php
<?php

//per la cache
//https://github.com/JosephSilber/page-cache

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\StaticController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\GalleriesController;
use App\Http\Controllers\ContactController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::middleware('page-cache')->get('/', [StaticController::class, 'index'])->name('static');
Route::middleware('page-cache')->get('/chi-siamo', [StaticController::class, 'about'])->name('about');
Route::middleware('page-cache')->get('/richiedi-assistenza', [StaticController::class, 'assistence'])->name('assistence');
Route::middleware('page-cache')->get('/cookie-policy', [StaticController::class, 'cookie'])->name('cookie');
Route::middleware('page-cache')->get('/privacy-policy', [StaticController::class, 'privacy'])->name('privacy');
Route::middleware('page-cache')->get('/servizi', [StaticController::class, 'services'])->name('services');
Route::middleware('page-cache')->get('/galleria', [StaticController::class, 'gallery'])->name('galleriesfront');

//Route::get('/', [StaticController::class, 'index'])->name('static');
//Route::get('/chi-siamo', [StaticController::class, 'about'])->name('about');
//Route::get('/richiedi-assistenza', [StaticController::class, 'assistence'])->name('assistence');
//Route::get('/cookie-policy', [StaticController::class, 'cookie'])->name('cookie');
//Route::get('/privacy-policy', [StaticController::class, 'privacy'])->name('privacy');
//Route::get('/servizi', [StaticController::class, 'services'])->name('services');
//Route::get('/galleria', [StaticController::class, 'gallery'])->name('galleriesfront');

//Route::middleware('page-cache')->get('/contatti', [StaticController::class, 'contact'])->name('contact');

//Route::get('/', [StaticController::class, 'index'])->name('static');
//Route::get('/chi-siamo', [StaticController::class, 'about'])->name('about');
//Route::get('/richiedi-assistenza', [StaticController::class, 'assistence'])->name('assistence');
//Route::get('/cookie-policy', [StaticController::class, 'cookie'])->name('cookie');
//Route::get('/privacy-policy', [StaticController::class, 'privacy'])->name('privacy');

//Route::get('/servizi', [StaticController::class, 'services'])->name('services');
//Route::get('/galleria', [StaticController::class, 'gallery'])->name('galleriesfront');

Route::get('/contatti', [StaticController::class, 'contact'])->name('contact');
Route::post('/contatti', [ContactController::class, 'store'])->name('contact.store');


//Route::get('/login', [AdminController::class, 'index'])->name('login');

Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function() {

    Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard');
    Route::get('/users/data/', [UserController::class, 'data'])->name('users.data');
    Route::resource('users', UserController::class);

    //roles
    Route::get('/roles/data/', [RoleController::class, 'data'])->name('roles.data');
    Route::resource('roles', RoleController::class);

    //pages
    Route::get('/pages/data/', [PagesController::class, 'data'])->name('pages.data');
    Route::resource('pages', PagesController::class);

    //galleries
    Route::get('/galleries/data/', [GalleriesController::class, 'data'])->name('galleries.data');
    Route::resource('galleries', GalleriesController::class);
});

Auth::routes();

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use DB;
use Yajra\DataTables\DataTables;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('permission:superadmin|admin|employee|client', ['only' => ['index','store']]);
        $this->middleware('permission:superadmin|admin|employee|client', ['only' => ['create','store']]);
        $this->middleware('permission:superadmin|admin|employee|client', ['only' => ['edit','update']]);
        $this->middleware('permission:superadmin|admin|employee|client', ['only' => ['destroy']]);

        $this->activeMenuRoles= true;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
//        $roles = Role::orderBy('id','DESC')->paginate(5);
//        return view('roles.index',compact('roles'))
//            ->with('i', ($request->input('page', 1) - 1) * 5);
        return view('roles.index', $this->data);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->permission = Permission::get();
        return view('roles.create',$this->data);
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:roles,name',
            'permission' => 'required',
        ]);
        $role = Role::create(['name' => $request->input('name')]);
        $role->syncPermissions($request->input('permission'));
        return redirect()->route('roles.index')
            ->with('success',__("app.roleCreatedSuccess"));
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $this->role = Role::find($id);
        $this->rolePermissions = Permission::join("role_has_permissions","role_has_permissions.permission_id","=","permissions.id")
            ->where("role_has_permissions.role_id",$id)
            ->get();
        return view('roles.show',$this->data);
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->role = Role::find($id);
        $this->permission = Permission::get();
        $this->rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.role_id",$id)
            ->pluck('role_has_permissions.permission_id','role_has_permissions.permission_id')
            ->all();
        return view('roles.edit',$this->data);
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'permission' => 'required',
        ]);
        $role = Role::find($id);
        $role->name = $request->input('name');
        $role->save();
        $role->syncPermissions($request->input('permission'));
        return redirect()->route('roles.index')
            ->with('success',__("app.roleUpdateSuccess"));
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
//        DB::table("roles")->where('id',$id)->delete();
//        return redirect()->route('roles.index')
//            ->with('success','Role deleted successfully');
        return response()->json([
            'status' => 'success'
        ]);
    }

    /**
     * Return all roles
     *
     * @return mixed
     */
    public function data() {
        $roles = Role::orderBy('id', 'asc')->get();

        return Datatables::of($roles)
            ->addColumn('action', function($row){

                $link = '';

                $link .= '<a href="' . route('roles.edit', [$row->id]) . '" class="btn btn-sm btn-info btn-circle"
                  data-toggle="tooltip" data-original-title="' . __("app.viewRole") . '"><i class="fa fa-pencil-alt" aria-hidden="true"></i></a> ';

                $link .= '<a href="javascript:;" class="btn btn-sm btn-danger btn-circle sa-params"
                  data-toggle="tooltip" data-role-id="' . $row->id . '" data-original-title="' . __("app.deleteRole") . '"><i class="fa fa-times" aria-hidden="true"></i></a> ';

                return $link;

            })
            ->editColumn(
                'name',
                function ($row) {
                    return ucfirst($row->name);
                }
            )
            ->editColumn(
                'email',
                function ($row) {
                    return '<a href="'.route('users.edit', $row->id).'">'.$row->email.'</a>';
                }
            )
            ->rawColumns(['name', 'action'])
            ->make(true);
    }
}

resources/views/roles/create.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">{{__("app.addNewRole")}}</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">{{__("app.addNewRole")}}</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <div class="card">
            <div class="card-header">
                <h3 class="card-title"><a class="btn btn-sm btn-primary" href="{{ route('roles.index') }}"> {{__("app.back")}}</a></h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                </div>
            </div>

            <div class="card-body">
                {!! Form::open(array('route' => 'roles.store','method'=>'POST')) !!}
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>{{__("app.name")}}:</strong>
                            {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>{{__("app.permissions")}}:</strong>
                            <br/><br/>
                            @foreach($permission as $value)
                                <label>{{ Form::checkbox('permission[]', $value->id, false, array('class' => 'name')) }}
                                    {{ $value->name }}</label>
                                <br/>
                            @endforeach
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                        <button type="submit" class="btn btn-primary">{{__("app.submit")}}</button>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </section>
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">{{__("app.addNewRole")}}</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">{{__("app.addNewRole")}}</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

            <div class="card">
                <div class="card-header">
                    <h3 class="card-title"><a class="btn btn-sm btn-primary" href="{{ route('roles.index') }}"> {{__("app.back")}}</a></h3>
                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                    </div>
                </div>

                <div class="card-body">
                    {!! Form::model($role, ['method' => 'PATCH','route' => ['roles.update', $role->id]]) !!}
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>{{__("app.name")}}:</strong>
                                {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>{{__("app.permissions")}}:</strong>
                                <br/>
                                @foreach($permission as $value)
                                    <label>{{ Form::checkbox('permission[]', $value->id, in_array($value->id, $rolePermissions) ? true : false, array('class' => 'name')) }}
                                        {{ $value->name }}</label>
                                    <br/>
                                @endforeach
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                            <button type="submit" class="btn btn-primary">{{__("app.submit")}}</button>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>

    </section>
@endsection

resources/views/roles/index.blade.php
@extends('layouts.admin')

@push('head-script')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
@endpush

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">{{__("app.roles")}}</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">{{__("app.roles")}}</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">

        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Title</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-bordered table-hover toggle-circle default footable-loaded footable" id="roles-table">
                    <thead>
                    <tr>
                        <th>@lang('app.id')</th>
                        <th>@lang('app.name')</th>
                        <th>@lang('app.action')</th>
                    </tr>
                    </thead>
                </table>
            </div>

            <div class="card-footer">
                <a class="btn btn-sm btn-success" href="{{ route('roles.create') }}"> {{__("app.addNewRole")}}</a>
            </div>

        </div>

    </section>
@endsection

@push('footer-script')
    <!-- DataTables  & Plugins -->
    <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('plugins/jszip/jszip.min.js') }}"></script>
    <script src="{{ asset('plugins/pdfmake/pdfmake.min.js') }}"></script>
    <script src="{{ asset('plugins/pdfmake/vfs_fonts.js') }}"></script>
    <script src="{{ asset('plugins/datatables-buttons/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables-buttons/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables-buttons/js/buttons.colVis.min.js') }}"></script>

    <script>
        $(function () {
            var table = $('#roles-table').dataTable({
                responsive: true,
                processing: true,
                serverSide: true,
                ajax: '{!! route('roles.data') !!}',
                language: {
                    "url": "<?php echo __("app.datatable") ?>"
                },
                "fnDrawCallback": function( oSettings ) {
                    $("body").tooltip({
                        selector: '[data-toggle="tooltip"]'
                    });
                },
                columns: [
                    { data: 'id', name: 'id' },
                    { data: 'name', name: 'name' },
                    { data: 'action', name: 'action' }
                ]
            });

            $('body').on('click', '.sa-params', function(){
                var id = $(this).data('role-id');
                Swal.fire({
                    title: "<?php echo __("app.sure") ?>",
                    icon: 'error',
                    text: "<?php echo __("modules.roles.deletesure") ?>",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "<?php echo __("app.yesdelete") ?>",
                    cancelButtonText: "<?php echo __("app.nocancel") ?>",
                    closeOnConfirm: true,
                    closeOnCancel: true
                }).then((result) => {
                    if (result.isConfirmed) {

                        var url = "{{ route('roles.destroy',':id') }}";
                        url = url.replace(':id', id);

                        var token = "{{ csrf_token() }}";

                        $.ajax({
                            type: 'POST',
                            url: url,
                            data: {'_token': token, '_method': 'DELETE'},
                            success: function (response) {
                                console.log(response.status);
                                if (response.status == "success") {
                                    // $.unblockUI();
                                    Swal.fire("<?php echo __("app.deleted") ?>", response.message, "success");
                                    table._fnDraw();
                                }
                            }
                        });
                    }
                })
            });

            @if ($message = Session::get('success'))
                const Toast = Swal.mixin({
                        toast: true,
                        position: 'top-end',
                        showConfirmButton: false,
                        timer: 3000,
                        timerProgressBar: true,
                        didOpen: (toast) => {
                            toast.addEventListener('mouseenter', Swal.stopTimer)
                            toast.addEventListener('mouseleave', Swal.resumeTimer)
                        }
                    })

                Toast.fire({
                    icon: 'success',
                    title: '{{ $message }}'
                })
            @endif

        });
    </script>

@endpush

resources/views/roles/show.blade.php
@extends('layouts.admin')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Role</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('roles.index') }}"> Back</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $role->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Permissions:</strong>
                @if(!empty($rolePermissions))
                    @foreach($rolePermissions as $v)
                        <label class="label label-success">{{ $v->name }},</label>
                    @endforeach
                @endif
            </div>
        </div>
    </div>
@endsection